model: labram_base_patch200_200
weight_decay: 0.05
batch_size: 64
lr: 5e-4
update_freq: 1
warmup_epochs: 5
epochs: 50
layer_decay: 0.65
drop_path: 0.1
rel_pos_bias: false       # --disable_rel_pos_bias
abs_pos_emb: true         # --abs_pos_emb
dataset: TUAB
qkv_bias: false           # --disable_qkv_bias
seed: 0

# Regression Head

# Dataset
DATA_ROOT_DIR: "/emo-eeg"
DATASET_NAME: 'FACED_standard'
CACHE_ROOT: "cache"
INPUT_CHA_NAMES: [
    "FP1", "FP2", "FZ", "F3", "F4", "F7", "F8", "FC1", "FC2", "FC5", "FC6", "CZ",
    "C3", "C4", "T7", "T8", "CP1", "CP2", "CP5", "CP6", "PZ", "P3", "P4", "P7",
    "P8", "PO3", "PO4", "OZ", "O1", "O2"
]
LABEL_DIM: 9
FS_ORI: 125
FS_TAR: 200
WINDOW_SIZE: 2.0
STRIDE: 1.0
BATCH_SIZE: 16
TRAIN_SUBS: [0,1,2]
VAL_SUBS: [0,1,2,3,4,5,6,7,8,9,10]

# Extract
run_name: 'default_run_name'
# finetune: ./runs/default_run_name/ckpt/checkpoint.pth
finetune: ./checkpoints/labram-base.pth

# Downstream Pipeline
ext: true
reg: true
cls: false