model: labram_base_patch200_200
finetune: ./checkpoints/labram-base.pth
weight_decay: 0.05
batch_size: 64
lr: 5e-4
update_freq: 1
warmup_epochs: 5
epochs: 50
layer_decay: 0.65
drop_path: 0.1
rel_pos_bias: false       # --disable_rel_pos_bias
abs_pos_emb: true         # --abs_pos_emb
dataset: TUAB
qkv_bias: false           # --disable_qkv_bias
seed: 0

# Regression Head

# Dataset
DATA_ROOT_DIR: "/emo-eeg"
DATASET_NAME: 'FACED_standard'
CACHE_ROOT: "cache"
INPUT_CHA_NAMES: ['FP1', 'FP2', 'FPZ']
LABEL_DIM: 3
FS: 200
WINDOW_SIZE: 2.0
STRIDE: 1.0
BATCH_SIZE: 16
TRAIN_SUBS: [1,2]
VAL_SUBS: [1,2]

# Training
run_name: 'default_run_name'
finetune_epochs: 20